#hic sunt dracones :)

[Device]

#set to 1 if values in Audio_Config are to be used
audio_config_values_valid = 1

#set to 1 if custom product, manufacturer and serial strings are to be used
serial_number_enable_control = 1

#beware, issuing wrong VID & PID may remove support for CM108B specific functions on some software relying on this information. It will be 
VID = 0x0d8c
PID = 0x0012
serial_number = 1234ABCD

#30 char max, only Latin-1 ?
product_string = Interface F4JNT
manufacturer_string = Atelier Froggy

#All volumes are in dB, conversion to hex is done in script
[Audio_Config]

#DAC: initial default volume -10, min -37 (inconsistencies in datasheet), max 0
DAC_initial_volume = -10
#1: Use values in EEPROM, 0: Use default
DAC_min_max_volume_valid = 1
DAC_min_volume = -37
DAC_max_volume = 0

#ADC: initial default volume 8, min -22 (inconsistencies in datasheet), max 23
ADC_initial_volume = 8
#1: Use values in EEPROM, 0: Use default
ADC_min_max_volume_valid = 1
ADC_min_volume = -22 
ADC_max_volume = 23 

#AA: initial default volume -7, min -23, max 8
AA_initial_volume = -7
#1: Use values in EEPROM, 0: Use default
AA_min_max_volume_valid = 1
AA_min_volume = -23
AA_max_volume = 8

#0: 22dB, 1: 12dB (default) 
boost_mode = 1 

DAC_shutdown = 0

#Undocumented function. 1:enabled, 0:disabled(default)
total_power_control = 0

#1:enabled (default), 0:disabled
MIC_high_pass_filter = 1

#Undocumented function. May have something to do with ADC synchronization. 1:enabled, 0:disabled(default)
MIC_PLL_adjust = 0

#Undocumented function. #1:enabled (default), 0:disabled
MIC_boost = 0

# 1: headset, 0: speaker
DAC_output_terminal = 0

#Beware, disabling the HID will disable EEPROM management and GPIO control !
hid_enable = 1

# USB remote wakeup. 1:enabled, 0:disabled(default)
remote_wakeup = 0

# Undocumented function.
EE_OPTION2 = 0